# The main goal is to understand the impact of the use of Inductive Methodology 4C/ID by answering the questions: 
#   1 - changing the learning methodologies from one mainly deductive (Direct Instruction[^1]) to another one mostly inductive (4C/ID [^2]), means what for your students? Who benefits? What are the pros and cons about this methodological decision?
#   2 - Should you, as a teacher of science and tech, move to implement the inductive strategy as your methodology for learning? 
#   3 - And if you do, what are the outcomes? What are the risks? What were the consequences for the student's academic results? 
#   4 - Is there a different impact between female and male? 
#   5 - And within the different grades?
#   6 - Student more adapted to school have benefit more with the use of 4CID methodology?


# CONCLUSIONS and REMARKS

(`under construction`)

The conclusions presented here focus more on the junior sample of school 1. So, **Overall**, as a teacher of science and tech, you should (or at least think about it) move to implement the inductive strategy as your methodology for learning because it improves the **Learning Transfer**, **academic results** with a huge impact on **lab practice**, except for the **Social Skills** [^readme-8].

However, there are **risks and concerns** to be accommodated during the process, namely:
1. for the student less adapted to the school system;
2. the classroom management referring to students behavior (see discussion);
3. in the **learning transfer** process the gains are more modest;
4. males gain less with this change.

[^readme-8]: Is there an underlying behavioral underlying effect?

**Bottom line**, if you don't want to take the risks, change conditional to have a student group more adapted to school or if you want to increase the lab practices skills. Futhermore, this work shows is that there is a slight advantage of using 4C/ID eLearning setting compare to Direct Instruction. In fact, there is a huge advantage of 4C/ID in Lab Practice in spite of the negative impact in Social Skills. It also shows that the students that are less adapted to school don't improve much unless for the Lab Practice. So, compare with a instructional design with 200 years (???) of reliability is something to higlight.

RISKS:

A major risk is for the less adapted students to school: there is a need to accommodate this. 

For the **Social Skills**, specifically in the aspect of following social and behavioral classroom rules, there is a major negative [\^6] impact in all samples: the risk of loosing control of the students group inside the classroom is real; however, note that the assessment were all positive: median change from 81 to 74%, which means that the behavior was above 50% and didn't represent a thread to the classroom learning environment.

CONCERNS:

In general, GRADE 7 and RANK 2 tends to benefit less then the other grades and rank 3;

# DISCUSSION

notes for discussion: - The conlsuions meet the goals and answer th research question? - Did I implemented the methods correctly? - Is there an underlying effect for the behav variable? - Conclusions for the stakeholders in the learning process: teachers, Policy implications and school management. - blearning change: team work impressible - Reiterate results - world research corroboration ; Future research Tie loose hands: Clarify, robustness; after 2015 there is a crash in the student behavior skills.: need extra data; social skills: all, ranks, grades, and gender follow the same pattern? students behavior effect

  ## NOTES and OBSERVATIONS
  ## Policy implications
  ## Future  arch
  ## Tie loose hands together
  # DOUBTS AND DISCUSSIONS
  ########## doubts and discussions
# 802!?!?!? - scale change
#Kendall correlation test, sometimes because of the random sample it gives results of depency...
#what to ? a for cycle and calcula probability of getting independency?
#rank 1, kendall ties!?



#NOTES

The inner goal of a teacher is always to have their students engaged in their subject, to have them wanted to know more, and tease their curiosity towards life and knowledge in general. The idea of changing the methodological strategy was compelling, not only because it seems a more natural way, more BBL suitable, to address the Science subject wording by adopting this 4C/ID learning flux strategy, but also to engage in its conceptual and mental model, that is, improve learning. So, when introducing concepts, there was a neuro network of lab experiences that facilitate that understanding, so important in Science subjects. What were the consequences for the student's academic results?


???RESEARCH QUESTIONS

The conclusions presented here focus on the junior sample of school 1 (table above). 

**Overall**, as a teacher of science and tech, you should move to implement the inductive strategy as your methodology for learning because it improves the **academic results** with a huge impact on **lab practice**.

However there are risks and concerns to be accommodated during the process, namely: 

  1. the less adapted to the school system;
  2. in the **behavior** aspect of the classroom managment and in the **learning transfer**;
  3. in less degree of concern, Grade 7 and males seems to benefit less from this change.

**Bottom of line**, if you don't want to have the less risks as possible, change if you have a student group more adapted to school and if you want to increase the lab practices skills.

RISKS:
  1. In the **learning transfer** and **academic results**, there is the risk that the less adapted to the school environment suffer more with this strategic change;
  2. For **behavior**, specifically in aspect of following social and behavioral classroom rules, there is a major negative [^???] impact in all samples: the risk of loosing control of the students group inside the classroom is real, but in this case, the assessment were all positive: median change from 81 to 74%, which means that the behavior was above 50% and didn't represent a thread to the classroom learning environment;

CONCERNS:
  1. There seems to be a positive effect only in GRADE 8 and FEMALE groups for the **learning transfer**, the other groups the change don't have any effect. 
  2. On the **behavior field** only grade 9 seems to get some positive effect;
  3. In general, Female gender group tend to benefit more them male;
  4. In general, RANK 3 tends to benefit more then the other rank groups;
  5. grade 9th benefit more then the other grades;
  
BENEFITS:
  1. In overall, the change has a positive impact on junior grade students for the **academic results**; 
  2. **Lab practice** has a large positive effect in all samples;

------------------------------

The answer is yes, you should, but... you need, according with this work, to take in account some crucial remarks, that related to the outcames and the risks, namely: 

1. In general, students will benefit from moving to an inductive methodology and, particularly, the 4C/ID used here;
2. Students transfer TEST and LAB improve in general;
3. Student's behavior suffers a little loss;
4. 8 graders benefit more...
5. Gender...
6. put the learning responsablity on the student...
7. When changing the methodology, some students feel lost: it's important to give some text support, using books or written documents (called Supportive information in 4C/ID methodology), in order for students to have a logical work flow line to follow.
8. Motivation and understanding improve, not only because of practical, hands-on, LAB activities but because students understand what the teacher discourse meanings is, when listening.´
9. The use of intensive ??? for learning objectives??? create a sense of control and the joy of achievement.

Remarks:
10. If you are using also bLearning you should be part of a team: it's overwhelming for one person alone, to manage, organize, create content, plan and assess the learning flux;
11. Using bLearning improves the time of individual exchange??? because the teacher can use their time to help students while they are following the online activities (MOODLE lessons, ????)
12. There is a descent curve starting in 2014 that can't be explained by the methodology difference
13. questions and other research paths????

It seems that the 4CID effect is not positive for all the variables neither for the overall perspective it seems that school 0 as better TEST grades them school 2, while there a jump when the 4CID is implemented; That is not so obvious for the LAB variable. Clearly that the BEHAV variable suuffers a loss with the implementation of 4CID. for the CLASS variable, after a positive effect it goes down, perhaps following the BEHAV variable only the LAB variable show an increase. The red dot and the skewness showed in figure 7, show that could be no positive overall 4C/ID effect and the sample are not normal, which corroborate upper analysis

Overall, over time, it seems that there is a negative 4C/ID effect. 
However, R^2 values are very weak. It can be seen that a school effect could be undeway these R2 low doesn't mean that the variables are dependent nor the 
There is some degree of correlation that doesn't permit to conclude of the variable dependency
The clear correlation between TEST and CLASS variable show that they are dependent and Kendal correlation test corroborates that variables are dependent but with a levell degree arround 20 to 40%: not high; meaning that the way the variables are assessed are different. They correlate, but at a low levell, showing a bad levell, which means that they were assessed with different techniques.the class test correlation is just a refence that we know, in advance, that there is a math relationship

data seems to be not normal, except the CLASS variable sample data don't behav as a normal distribution under both tests, nor if we do the same analysis for the school 0 and shcool 1. Meaning that we should use a non-parametric . diferent SAMPLES for the 4C/ID treatment effect
sample data don't behav as a normal distribution under both tests, nor if we do the same analysis for the school 0 and shcool 1. Meaning that we should use a non-parametric 

only for the most **robust and reliable sample** used in this work: in fact the sample is much larger. So, they show results about the JUNIOR sample for SCHOOL 1, which means:

  1. not having the school effect [^readme-7];

[^readme-7]: Is there an underlying behavioral underlying effect?

  2.  the sample has students with the same age;
  3.  it doesn't have the problem of using the less numbered entrances of the junior high students sample.

# DISCUSSION 

Reiterate results
Policy implications
Future research
Tie loose hands???
world research corroboration???
Clarify
robustness

# KEYWORDS

Inductive learning strategy; 
4C/ID; 
Direct Instruction; 
Learning Flux - Concept Maps; 
Statistical Non-parametric Inference; 
Quantitative and Qualitative analysis
Learning transfer - the hability of pass information to the students measured in the tests (online or paper supported),directly related to the TEST avriable
Lab Practice - Laboratory activities directly related to the variable LAB
Behavior - Following social and behavioral classroom rules directly related to the BEHAV variable.
Academic results - weight average variable directly related to the other variables: TEST, LAB and BEHAV.

# REFERENCES

[^1] https://github.com/fqantonio/GoingInductive
[^2] https://cmap.ihmc.us/
[^3] https://www.4cid.org/
[^???] there is a need to make some anlysis of this data because it seems that there is an underlying effect

