
# ABSTRACT

Should you, as a teacher of science and tech of young students, **move to an inductive strategy**, for the learning design flow with all the activities chronologically organized, even if the setting is bLearning? In overall, the **answer is yes**, that is, 4C/ID eLearning setting as some advantages to Direct Instruction but with some remarks. If you decide to do it, there will be specific impacts for the students that need to be **accommodated**, as well as implications for the stakeholders in the learning process: policy makers and school management. The sample covers 12 years of teacher data assessment, during the period 2003 to 2018, with conclusions about the impact in the Learning Transfer, Lab Practice, Social Skills and Academic Results.

> Education is the most powerful weapon which you can use to change the world. 
>
>                                                 Nelson Mandela

**Keywords** Inductive learning strategy; 4C/ID; Direct Instruction; Learning Flow; Statistical Non-parametric Inference; academic results; learning transfer; behavior; lab practice; Cognitive Load Theory; Multi Intelligence Theory; Brain Based Learning; bLearning.

# GOALS, RESEARCH QUESTIONS and HYPHOTESIS

The **main goal** is to understand the impact of the use of Inductive Methodology four component instructional (4C/ID) in a bLearning setting, by answering the following **research questions**:

1 - changing the learning methodologies from one mainly deductive, denominated by Direct Instruction (Merrill, 2007) to another one mostly inductive, Merriënboer's 4C/ID design theory (van Merriënboer, Kirschner, 2007), means what for students learning outcomes? Who benefits? What are the pros and cons about this methodological decision? What are the implications for the stakeholders?

2 - Should you, as a teacher of science and tech, move to implement the inductive strategy as your methodology for learning?

3 - And if you do, what are the outcomes? What are the risks? What were the consequences for the student's academic results?

4 - Is there a different impact on gender?

5 - And within the different grades?

6 - Student more adapted to school benefit more?

The **hypothesis** is that this change will have a positive impact in all learning areas because, in overall, it is based on the 4C/ID methodology that, in itself, is anchored on Brain Based Learning (BBL), Cognitive Load Theory (CLT), Multi-Intelligence Theory (MIT) and Multimedia Learning (ML).

# INTRODUCTION

The work presented here deals with the impact of changing from a mostly deductive type of methodology to a mostly inductive one: more precisely, this means a major change from a, **direct instruction** (Merril, 2007) classroom setting to an inductive strategy, **four components instructional design** (4C/ID) (Van Merrienboer, Clark, Coock, 2002), in a bLearning environment (Mayer, 2005). This leads directly to a major and crucial teacher concern that transform into the main **research question**: what are the accommodations, risks and concerns about the impact on students learning that you have to deal, if you make this strategic change?

Since this is a longitudinal data sample, Junior and junior high for the physics and chemistry content of the Portuguese school curriculum, the **conclusions** extrapolation should be used carefully.

The data used in this work was gathered over 12 years, in the period 2003 to 2017, from actual teacher day-to-day practice assessments about students **Learning Transfer**, **Lab Practice**, **Classroom Behavior**, that include Social Skills, and **Academic Results**. 

# EDUCATIONAL CONTEXT

After starting to be interested about the different ways students learn I came across with the work of Felder´s learning styles (Felder; Silverman; 1988) and Wiley's Learning Objects (Wiley, 2002). These paper's showed me a complete list of different methodologies with different points of views: the inductive ones seems very promising and more adapted to the way brain learns. 

Furthermore, the readings about alternative **educational methodologies** went on, into the Cognitive Load Theory (Sweller, 1998), Brain Based Learning[\^2] (Jensen, 2005), Gardner Multi-Intelligence Theory (Gardner, 2011), eLearning (Garrison, Anderson 2003) and four component instructional design (4C/ID) (Van Merrienboer, Clark, Croock, 2002). After four years of readings and tests, in 2013 the 4C/ID methodology was applied and a bLearning environment online set with MOODLE Learning Management System (LMS) (Rice, 2006). Lessons were organized and were mostly accomplished in the classroom: fewer logs into the system were from outside.

This work includes junior and junior high students of two different schools data, from different regions, for the chemistry and physics subjects of the Portuguese curriculum, in the time scale 2003 to 2017. Raw data was gathered during 12 years, from actual day-to-day assessment registering in three different areas: transfer tests, lab practice and classroom behavior.

# MOTIVATION

Most of the time the professional, specific, **day-to-day teacher work** data is rarely or never investigated, at least, in the Portuguese educational environment. For the teachers, there is no time to look back and work through the data results, the qualitative remarks, or through the statistics. And, as a consequence, no robust conclusions are drowned and worse, it's normal not to share it.

My **personal motivation** is to know if the strategic decisions I did in 2008 were positive for my students: did they benefit from the educational strategic change? It was a global benefit or some groups benefited more? Does anyone have the same kind of research for comparision? Can anyone corroborate this results or criticize them? Sharing is the way to go to find knowledge.

The concept map's software cmap tools[^readme-2] was used for the design of the learning flow maps and they are presented online[^readme-3] showing the four components and the structure based in the four component instructional design (4C/ID), described in the book *Ten Steps to Complex Learning* (van Merriënboer; Kirschner, 2007). This maps are used since 2012, included.

[^readme-2]: <https://cmap.ihmc.us/>

[^readme-3]: Flow charts (missing details to be updated) Data base sample (R data frame): <https://cmap.ihmc.us/> ;



# NOTES

# Summary

- [ ] why is it interesting/important
- [ ] clearly state the research question and describe (in nontechnical terms) how you will analyze
- [ ] What others have done
- [ ] pre-results

#FOCUS
- [ ] Research questions
- [ ] How will it be analysed

This is the site with all the work done for the paper "Going Inductive?": the documentation generated and the code in R using RStudio, statistical analysis methods included is also available here as well as the ongoing documentation (wiki), sample data and raw data.

Most of the time the professional, specific, day-to-day teacher work gathered data is rarely or never investigated. At least in the portuguese educational environment. For the teachers, there is not much time to look back and work through the data results, the qualitative remarks, or through the statistics. And, as a consequence, no robust conclusions are possible. Worse, even if someone did it, it's normal to not share it. Research and discussion with peers are crucial to better adjust our decisions regarding the way students learn today. The way learning happens and motivation changes, are so fast! So, teaching, at least in Portugal, is a very solitary job with all of its directly related drawbacks.

On the other end, the organizational environment of schools and teachers in Portugal doesn't help either. Focused on managing the schools as enterprises with a lot of controlling bureaucracy, putting numbers and paperwork ahead of the crucial and significant decisions around teaching, real assessment is barely used, and when it is, its just at the university level. This means:
1. The crucial planning and individual teacher-student interaction is less important for this organization;
2. Time spent on research and discussions is useless: numbers constrain our job, of course, it's normal, but with the same money we can do better if we can get together and discuss the way we could be organized.

Luckily, the knowledge and the tools available online today, permit that we can go further with peer contribution and go beyond a simple Average Treatment Effect (some of us, at least do some mean computations): statistical knowledge is not something that we are prepared for and the statistical tools are very expensive. Now this tools are available in opensource licences: so, time is crucial: teacher need it to study, get the necessary knowledge and interpret the results. And publish it.

Back to the issue here, my personal goal was to know if the strategic decisions I did in 2008 were positive for my students. The motivations are at least two: 

1. Did my students benefit from the educational strategic change? It was a global benefit or some groups benefited more.
2. To share this conclusion in order to exchange knowledge with others around the world, and see if they corroborate with this findings.

The organizational environment of schools and teachers in Portugal doesn't help this type of research work. Focused on managing the schools as enterprises with a lot of controlling bureaucracy, putting numbers and paperwork ahead of the crucial and significant decisions around teaching, real assessment is barely used, research follows the same pattern, and when it happens, its just shared at the university level. Meaning:

1 - The crucial planning and individual teacher-student interaction is less important for this organization;

2 - Time spent on research and discussions is useless: numbers constrain our job, of course, it's normal, but with the same money we can do better if we can get together and discuss the way we could be organized.

In my view, both research and discussion with peers are crucial to better adjust our decisions regarding the specific strategies, activities and learning flux presented that must also be adapted to the way students learn today. The way learning happens and motivation changes, is so fast! So, teaching, at least in Portugal, is a very solitary job with all of its directly related drawbacks.

Luckily, the knowledge and the tools available online today, allows us to go further with peer contribution, beyond a simple Average Treatment Effect (some of us, at least, do some mean computations): statistical knowledge is not something that we are prepared for and the statistical tools are very expensive. Today, this tools are available with opensource licences: so, time is crucial: teacher need it to study, get the necessary knowledge and interpret the results. And publish it!


# Research question

Should you, as a teacher of science and tech, move to implement the inductive strategy as your methodology for learning? And if you do, what are the outcomes? What are the risks? What were the consequences for the student's academic results? 

# Milestones

| date     | Action | Notes|
| ----------- | ----------- |-----|
|August 2019 | Gathering data ||
|January 2020  | Cleaning data ||
|2019-2021|EDX course|Statistical procedures|
|September 2022|data analysis: descriptive data summary|testing the limits|
|September 2022|Statistical Analysis results|Normality; RDD; inference; regression|
|October 2022|Writing|Paper chapters: summary; introduction; #DATA; Descriptive Analysis; Normality; METHODS;RESULTS|
|November 2022|Conclusion and EDIT; Glossary; references||
|December 2022|Readings||
|January 2023|send to be [hopefully] published with peer review|postponed|

Note: for several contextual reasons this went on until april 2023, when the paper was to be ready for experts to read it for the first time.

| date     | Action | Notes|
| ----------- | ----------- |-----|
| April 2023      | Draft ||
| June 2023  | EDIT, EDIT, EDIT ||
|September|Release the paper to journal peer review||

# State of the art


# Context
Since 2003 the search for other methodologies available brings me to the Cognitive Load Theories, Brain Based Learning (BBL), Gardner's Multiintelligence Theory (MIT),  Emotional Intelligence approaches of (???) and bLearning. These  readings started with the work of FELDER []. Until then I use laboratory work exploration Direct Instruction, lectures, exercises, discussions, inquiries, challenges or a misture of all of this. The idea of inductive edu environment took me to 4C/ID four component instructional design of Merrionboer???. Since then, it took me four years to integrate this ideas and build concrete edcuational workflows by using CMAP tools until there was same mastering of the approach and in 2013, in full speed using also a bLearning environmet wth MOODLE.

The inner goal of a teacher is always to have their students engaged and motivated in their subject, to have them wanted to know more, and tease their curiosity towards real life applications and knowledge. At a point, I felt the need to study more in order to know how to better engage students with their learning process.

Since 1992, I work at several different public schools as a teacher of chemistry and physics of young student, from Junior to Junior High School. I start to teach Science, without any background on educational methods, only with what I learned as a student, with what I think it's a better way to learn: organizing lab activities, hands-on situations, trying to have students in an informal, trial-and-error environment, having them try their hypothesis, whatever they are, even the most naive, even when schools didn’t have the laboratory facilities. Sometimes, students were engaged by trying to organize and run a small lab projects. 

Along with this, I organized the Lab Aberto project, after school program, continuing the idea of letting students trial and error environment, consequently, to profit with their errors and own conclusions. 

???The first focuses on the Direct Instruction[^1] (DI) traditional methodologies, Brain Based Learning (BBL)[^2], Multiple Intelligence[^3] (MI) theory and the former, the 4C/ID[^4] instruction design proposed by Merrionboer , based on Cognitive Load Theory[^5] (CLT) and inductive educational strategy. 

Multimedia learning

In 2005, I started to introduce the concept of Learning Objects from ()??? along with eLearning environment, exploring bLearning (based on MOODLE built-in activities), reading about Brain-Based Learning (BBL), Multi-intelligent theory (MI), Learning Styles (LS), Emotional Intelligence (EI). During this readings I found in the paper of FELDER (???) several different methodologies, inclunding the inductive approach which seems appealing. After that,??? I found the book 4C/ID of Merrionboer, talking about Inductive Learning Methods (ILM): only them I noticed that I used only deductive Learning Methodologies (DLM). Consequently, I found several other educational methods but on strike me more, the inductive one. So, Cognitive Load Theory were there already, the idea of learning flux was there to, because this 4C/ID needed concept maps toolto organize all the paths if you want to addapt this to a bLearning environment: anchor points, task practices, supoortive information, assessment, recurrent and non-recurrent learning objectives. All of this organized in time and in more deep and learning conceptual subject depth, or from concrete to concept, and from simple to complex, where scaffolding is a major concern.

Merrionboer blueprint,  has a steep learning curve (for me anyway), explain is theory based on the idea that we need to think about learning by starting with (almost) real practical problems situations, moving towards the concepts in time but going deep into to more complex issues related with the subject, identifying anchors, recurrent and non-recurrent learning objectives, given time for automatization procedures, and give same generalization environment recurring to variability to facilitate the integration of knowledge and skills. Cognitive load theory is of utmost importance because it proposes scaffolding, that is, taking care of the amount of information, prior knowledge and level of difficulty that is proposed in the learning task.

During the course of this work there was the need to engange througout data science knowledge analysis, so I took the online course EDX and then at MTx [^3].???

## Methodologies: changing over time.
|year| Methodology     | Description | Notes|
|------| ----------- | ----------- |-----|
| 2003-2007| Personal instruction: what I believe to be the best way to teach and to learn     | Lab Experimentation, expositive, lab reports, exercises, organized with the knowledge logic in order to acquire more and more information from concepts to concrete activities ||
|2008-2010|Direct instrution|Something with extensive research on it and based on more then 200 years experimental findings can be summarized on these principles: Task centered approach; prepare pupils to be ready; Activation principle (prior knowledge): present the new lesson; Demonstration Principle: associate it with prior knowledge; Application Principle: use examples; Integration Principle: test pupils to ensure they learn it;|([Merrill, 2007](https://mdavidmerrill.files.wordpress.com/2019/04/task_centered_strategy_published.pdf)); BBL; emotion; MI|
|2010-2013|Personal instrution +|Adding to the second row: LO, MOOdlE, BBL, MI, Emottional intelligence, concpetual maps, blearning flux|Transition to inductive methodology were all of this is already in place with the 4C/ID method|
|2013-2017| Inductive Methodology | 4C/ID methodology implies designing a learning flux with four components in mind, in two directions: practice to concepts (time schedule) and simple to complex (learning deeper and more complex knowledge): it means identifying crucial moments and design a lot of repetitive activities in order to master redundant/transversal learning objectives. In this design, it's important to identify anchor moments that serve as connector to other parts of the lessons |the learning include bLearning environment, merrionboer|

## Learning Flux

Cmap tools???


# Glossary

4C/ID instruction
transfer tests, 
behavior skill
social skills
Recurrent goals

# References

[^1]: Direct Instruction

[^2]: Brain Based Learning (BBL).

[^3]: Multiple Intelligence (MI) theory 

[^4]: 4C/ID[ instruction design proposed by Merrionboer.

[^5]: based on Cognitive Load Theory

[^6]: [Data Analysis for Social Scientists, MITx online](https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+3T2022/home).

[^7]: https://www.r-project.org/.

===============
Organize!?!?!

EDU Theory

academic results; 

learning transfer; behavior; lab practice; 

Cognitive Load Theory; 


Multi Intelligences Theory; 

Brain Based Learning;


Instructional Design
https://pz.harvard.edu/resources/frames-of-mind-the-theory-of-multiple-intelligences

https://www.semanticscholar.org/paper/Cognitive-Architecture-and-Instructional-Design-Sweller-Merrienboer/efa6ed36bfeaccb63b5e408c976bea0961873f90#citing-papers

https://en.wikipedia.org/wiki/Cognitive_load#cite_note-Sweller_et_al.,_1998-7

https://www.amazon.es/-/pt/dp/0805857931/ref=sr_1_2?keywords=ten+steps+to+complex+learning&qid=1684935087&sprefix=ten+steps%2Caps%2C125&sr=8-2

https://www.daveswhiteboard.com/archives/1899

https://link.springer.com/article/10.1007/s10984-021-09373-y

https://journals.sagepub.com/doi/10.2466/pms.1997.84.3.784

https://www.sciencedirect.com/science/article/abs/pii/S0747563201000139?via%3Dihub

https://www.tandfonline.com/doi/abs/10.1080/69032000072809?journalCode=tsed20

https://link.springer.com/article/10.1007/BF02504799

https://www.tandfonline.com/doi/abs/10.1080/13803610500110125?journalCode=nere20

https://onlinelibrary.wiley.com/doi/10.1002/acp.1250

https://www.sciencedirect.com/science/article/abs/pii/S095947520600017X?via%3Dihub

https://www.tandfonline.com/doi/abs/10.1207/s15326985ep4102_1

https://link.springer.com/article/10.1007/s11423-017-9539-9

https://www.sciencedirect.com/science/article/abs/pii/S0959475207000497?via%3Dihub

https://link.springer.com/article/10.1007/s11423-007-9085-y

https://www.sciencedirect.com/science/article/abs/pii/S0747563208002227?via%3Dihub

https://www.sciencedirect.com/science/article/abs/pii/S0747563208002203?via%3Dihub

https://www.sciencedirect.com/science/article/abs/pii/S0747563210001664?via%3Dihub

https://www.tandfonline.com/doi/full/10.3109/0142159X.2014.889290

https://link.springer.com/chapter/10.1007/978-3-319-28197-1_30

https://www.informingscience.org/Publications/2281

https://journals.lww.com/academicmedicine/Fulltext/2015/11000/Designing_Evidence_Based_Medicine_Training_to.13.aspx

Blearning
https://dl.acm.org/doi/10.1145/3279720.3279739
https://link.springer.com/article/10.1007/s10648-014-9262-6

https://www.tandfonline.com/doi/abs/10.1080/00461520.2013.804395

Inductive learning strategy; 

4C/ID; 

https://www.researchgate.net/publication/225798787_Blueprints_for_complex_learning_The_4CID-model

Direct Instruction; 

Learning Flux; 

Statistical 

Non-parametric Inference; 




