# METHODS

The **statistical analysis** methods uses R code software in the RStudio[^readme-4] IDE release and starts with a exploratory data analysis (EDA): a descriptive summary of the quantitative data and several plots showing patterns and relationships between variables. Afterwards there is a data normality and sample independence investigation. 

The principal methodology used is the non-parametric inferential treatment effect, but there is a discussion towards the non-parametric regression inference, regression discontinuity design and clustering. this last ones just to try to corroborate the upper first results. For this, it was used a data base[^readme-5] and 3 learning outcomes variables: transfer learning, laboratory practice and social skills, addressed respectively by 3 variables, TEST, LAB and BEHAV. The CLASS variable is directly related to the academic results and is a weigth average of TEST, LAB and BEHAV. TEST, LAB and BEHAV. This variables were assessed by paper and online transfer testing and in classroom observational paper registering forms (Koretz, 2008).

[^readme-4]: RStudio, <https://posit.co/products/open-source/rstudio/>

[^readme-5]: there was a need to make some analysis of this data sample group in order to conclude if there is an underlying school effect: in fact there is a difference confirmed with 95% confidence under the null. <https://github.com/fqantonio/GoingInductive/tree/main/DATA>

# NOTES


The conclusion was based on the usual statistical analysis and qualitative assessement notes using data from the usual day-to-day teacher database, spreadsheets assessments, notes, registers, inquiries, and teacher interactions with the students. This work, as well as the raw data, is also presented on the blog “https://4cidchange.edublogs.org/” and in this GitHub account. The quantitative assessment used statistical inference made with R software tool [^4] and is based on three learning outcomes: transfer tests (TEST), behavior (BEHAV), and lab skills (LAB). Two groups are compared groups, with and without the application of 4CID methodology (M4CID), in GENDER, RANK and SCHOOL. 

Goals
Describe the methods
no normal, Wilcox
errors not normal, no heterochedasticity???, no Regression discontinuity design
??? Triangulation ???
??? Balance methods ???

Conclusion: samples not normal but idenpendent: so, non-parametric inferene: wilcoxon can be used because of independency

# Software

In this work, I use R in the RStudio distribution. Mostly because it's "free" but also because it's really adaptable to what we want to do.

RStudio
2023.03.0 Build 386
© 2009-2023 Posit Software, PBC
"Cherry Blossom" Release (3c53477a, 2023-03-09) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36


# References
INTERNET
# STATS: https://courses.edx.org/dashboard/programs/71c95834-f6df-4f78-8cd7-c6461dd9b1d4/
# ggplot http://rafalab.dfci.harvard.edu/dsbook/ggplot2.html
# ggplot https://www.youtube.com/watch?v=1GmQ5BdAhG4 
# normal distrubution https://www.kdnuggets.com/2018/07/explaining-68-95-99-7-rule-normal-distribution.html
# normal distrb. plot https://steemit.com/programming/@dkmathstats/creating-normal-distribution-plots-with-r-programming
# CLT http://genomicsclass.github.io/book/pages/clt_and_t-distribution.html
# t-test http://genomicsclass.github.io/book/pages/t-tests_in_practice.html
# graphics ggplot https://r4ds.had.co.nz/graphics-for-communication.html
# graphics ggplot https://ggplot2.tidyverse.org/
# non-parametric regression http://users.stat.umn.edu/~helwig/notes/smooth-notes.html#need-for-np-regression
# Histogram with kernel density estimation https://r-charts.com/distribution/histogram-density-ggplot2/?utm_content=cmp-true
# Exploratory Data Analysis http://genomicsclass.github.io/book/pages/exploratory_data_analysis.html 
# Rstudio and github https://resources.github.com/github-and-rstudio/ 
# ggplot2 cheat sheet: https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf
# ggplot2: https://ggplot2.tidyverse.org/ 
# grid graphics: https://bookdown.org/rdpeng/RProgDA/the-grid-package.html
# Independent samples and hypothesis testing: https://datatab.net/tutorial/dependent-and-independent-samples
# non-parametric assumptions: https://bookdown.org/mandyyao98/bookdown-demo-master/lecture-9-non-parametric-methods.html
# correlation test: https://statsandr.com/blog/correlation-coefficient-and-correlation-test-in-r/#correlation-test
# Wilcoxon Rank Sum and Signed Rank Tests https://stat.ethz.ch/R-manual/R-devel/library/stats/html/wilcox.test.html
# Mann–Whitney U test https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Assumptions_and_formal_statement_of_hypotheses
# Non parametric tests: https://bookdown.org/siju_swamy/Stat_Lab/correlation-and-regression-analysis-in-r.html#correlation-analysis 
# Regression tools: https://ds4ps.org/pe4ps-textbook/docs/index.html
# Regression: https://stats.stackexchange.com/questions/381158/getting-equation-for-lm-ggplot-geom-smooth-with-multiple-levels
# Regression: https://www.datacamp.com/tutorial/linear-regression-R?utm_source=google&utm_medium=paid_search&utm_campaignid=20068300784&utm_adgroupid=152527239790&utm_device=c&utm_keyword=&utm_matchtype=&utm_network=g&utm_adpostion=&utm_creative=657040117338&utm_targetid=dsa-1947282172981&utm_loc_interest_ms=&utm_loc_physical_ms=1011751&utm_content=dsa~page~community-tuto&utm_campaign=230119_1-sea~dsa~tutorials_2-b2c_3-s-eu_4-prc_5-na_6-na_7-le_8-pdsh-go_9-na_10-na_11-na-mayftyc23&gclid=EAIaIQobChMIkI64lYGB_wIVA5xoCR0rngkIEAAYASAAEgInF_D_BwE
# RDD: https://rpubs.com/phle/r_tutorial_regression_discontinuity_design
# RDD: https://bookdown.org/carillitony/bailey/chp11.html
# RDD: https://ds4ps.org/pe4ps-textbook/docs/p-060-reg-discontinuity.html

Size effect: https://rpubs.com/abova/nptest 