# RESULTS
This file contains the results of the inference statistical analysis methods used in this research work. The initial tables resume the work. The latest present the same results but with more details. 

## Inference Analysis Table Resume
The symbols +, ~ and - in the table represent a positive treatment effect, no effect and a negative treatment effect.

| SAMPLE| TEST | LAB | BEHAV | CLASS | OBSERVATIONS/NOTES |
|:------------|:------------:|:------------:|:------------:|:------------:|:------------:|
| All sample                      | \-   | \+  | \-    | \-    | School effect identifyed                                               |
| Junior (school effect)          | \~   | \+  | \-    | \~    | school 1 with 4C/ID variable 1                                         |
| Junior and junior high          | \-   | \~  | \-    | \-    | junior and junior high school 0 and 1 (exclude school 1 without 4C/ID) |
| All sample (school effect)      | \-   | \+  | \-    | \-    |                                                                        |
| SCHOOL 1 junior and high junior | \~   | \+  | \-    | \+    |          |
| *Junior for school 1*             | \+ (54 to 58)  | \+ (53 to 66)  | \- (81 to 74)    | \+ (59 to 62)    |   Median values presented in %; AFTER this road sample is junior grade for SCHOOL 1                                     |
| GRADE 7                          | \~   | \+ (56 to 64)  | \- (77 to 71)   | \~    |                   |
| GRADE 8                         | \+ (54 to 58)   | \+ (55 to 68)  | \- (85 to 60)   | \~    | M4CID=="1", 71 entrances, less then 100 entrances|
| GRADE 9                         | \~   | \+ (44 to 66)  | \+ (80 to 85)   | \+ (55 to 64)   |          |
| RANK 1                          | \- (34 to 29)  | \+ (26 to 35) | \- (65 to 50)    | \- (39 to 37)    |           |
| RANK 2                          | \~   | \+ (51 to 62) | \- (80 to 67)    | \~    |            |
| RANK 3                          | \~   | \+  (73 to 80) | \- (94 to 90)   | \+ (77 to 81)    |            |
| FEMALE                          | \+ (54 to 56)   | \+ (52 to 70)  | \~    | \+ (59 to 67)    |          |
| MALE                            | \~   | \+ (53 to 62) | \- (81 to 66)    | \~    |          |

TABLE ???: Legend: + means positive effect, -, negative effect and ~ no effect

| Variable | + | ~ | -| SAMPLE + | no effect sample | sample - | Notes | 
| TEST (Learning Transfer) | 21% | 50% | 29% | Junior, 8th grade and FEMALE ||
| LAB (Lab practice) |93%|7%|0%||all samples|Junior and Junior High|no samples||
| BEHAV (Following social and behavioral classroom rules)|7%|86%|7%|GRADE 9|FEMALE|REMAINING SAMPLES|||
| CLASS |29%|36%|29%|SCHOOL 1 junior and high junior; 9th grade; FEMALE|Junior (school effect); grades 7 and 8|RANK 2; MALE |All sample; junior; RANK 1 and 3|||

## Sample JUNIOR for SCHOOL 1
The next two tables present the results for the most reliable sample used in this work. This is because it only uses JUNIOR sample for SCHOOL 1, which means not having the school effect nor the problem of using the less numbered entrances of the junior high sample. 

| SAMPLE | TEST | LAB | BEHAV | CLASS | OBSERVATIONS/NOTES |
|:------------|:------------:|:------------:|:------------:|:------------:|:------------:|
| *Junior for school 1*             | \+   | \+  | \-    | \+    | AFTER this road sample is junior grade for SCHOOL 1                                                                        |
| GRADE 7                         | \~   | \+  | \-    | \~    |                                                                        |
| GRADE 8                         | \+   | \+  | \-    | \~    | M4CID=="1",#71 entrances, less then 100 entrances                      |
| GRADE 9                         | \~   | \+  | \+    | \+    |                                                                        |
| RANK 1                          | \-   | \+  | \-    | \-    |                                                                        |
| RANK 2                          | \~   | \+  | \-    | \~    |                                                                        |
| RANK 3                          | \~   | \+  | \-    | \-    |                                                                        |
| FEMALE                          | \+   | \+  | \~    | \+    |                                                                        |
| MALE                            | \~   | \+  | \-    | \~    |              |

| Variable | + | ~ | -| SAMPLE + | no effect sample | sample - | Notes | 
| TEST (Learning Transfer) | 22% | 56% | 0% | All Junior sample, 8th grade and FEMALE |GRADE 7, 9; |RANK1||
| LAB (Lab practice) |100%|0%|0%||all samples||||
|BEHAV (Following social and behavioral classroom rules)|11%|11%|78%|GRADE 9|FEMALE|Junior; GRADE 7 and 8; all RANKs; MALE ||
|CLASS |33%|44%|22%|junior; 9th grade; FEMALE|grades 7 and 8; RANK 2 e MALE|RANK 1 and 3 ||

## Quantitative
From this session on, the tables presented, details all the specific results from the analysis statistical methods used. Remember that, in this work, the Treatment effect implies the presence of the methodology 4C/ID, variable M4CID =1: the control sample, implies direct instruction methodology, signalized with M4CID = 0;

table 11 : computed school differences for the junior sample school 0
and 1 without 4C/ID methodology

### Data

| Parameters | TEST   | LAB   | BEHAV  | CLASS | RANK  | RANDOM |
|------------|--------|-------|--------|-------|-------|--------|
| Min.       | 11.00  | 0.0   | 29.00  | 14.40 | 1     | 0      |
| 1st Qu.    | 50.00  | 48.0  | 66.00  | 54.50 | 1     | 28.00  |
| Median     | 62.00  | 60.0  | 78.00  | 63.60 | 2     | 53.00  |
| Mean       | 62.07  | 59.5  | 76.21  | 64.13 | 2.069 | 51.78  |
| 3rd Qu.    | 75.00  | 73.0  | 88.00  | 73.60 | 3     | 76.00  |
| Max.       | 100.00 | 100.0 | 100.00 | 98.70 | 3     | 100.00 |

| Condition         | Observations |
|-------------------|--------------|
| for each variable | 1157         |
| without M4CID     | 868          |
| with M4CID        | 289          |

| Sample     | Mean without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes                                    |
|------------|------------|------------|------------|------------|------------|
| All sample | greater                                                   | CLASS    | 0.4358           | no effect    | Does the variable SCHOOL as same effect? |
| All sample | greater                                                   | TEST     | 0.01419          | negative     | Does the variable SCHOOL as same effect? |
| All sample | less                                                      | LAB      | 1.341e-10        | positive     | Does the variable SCHOOL as same effect? |
| All sample | greater                                                   | BEHAV    | 5.937e-06        | negative     | Does the variable SCHOOL as same effect? |

Discussion: perhaps the school differences as some effect here

## Compare schools without 4C/ID

### DATA

| Condition                | Observations |
|--------------------------|--------------|
| Schools without M4CID    | 868          |
| school 0 (without M4CID) | 474          |
| school 1 (without M4CID) | 394          |

### RESULTS

| Sample                | Mean school 0 is greater/less/equal than school 1? | Variable | p-value (Wilcox) | School effect | Notes                            |
|------------|------------|------------|------------|------------|------------|
| Schools without 4C/ID | greater                                            | CLASS    | 2.2e-16          | positive      | School 0 as a greater CLASS mean |
| Schools without 4C/ID | greater                                            | TEST     | 2.2e-16          | positive      | School 0 as a greater TEST mean  |
| Schools without 4C/ID | greater                                            | LAB      | 6.946e-16        | positive      | School 0 as a greater LAB mean   |
| Schools without 4C/ID | less                                               | BEHAV    | 8.526e-06        | positive      | School 0 as a less BEHAV mean    |

Discussion: schools are different in all of the variables, so it's
better to use school 1 only to assess the 4C/ID effect.

## Inference for SCHOOL 1 with or without 4C/ID

### DATA

| Condition                | Observations |
|--------------------------|--------------|
| Schools 1                | 683          |
| school 1 (without M4CID) | 394          |
| school 1 (with M4CID)    | 289          |

### RESULTS

| Sample                 | Mean without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes                                                                               |
|------------|------------|------------|------------|------------|------------|
| sample with SCHOOL = 1 | less                                                      | CLASS    | 6.394e-06        | positive     |                                                                                     |
| sample with SCHOOL = 1 | less                                                      | TEST     | 6.394e-06        | positive     |                                                                                     |
| sample with SCHOOL = 1 | less                                                      | LAB      | 2.2e-16          | positive     |                                                                                     |
| sample with SCHOOL = 1 | less                                                      | BEHAV    | 0.5001           | no effect??? | For the 100 sample size analysis, p-value = 0.000376, so there is a positive effect |

## Inference for SCHOOL 1, gender Male, with or without 4C/ID

### DATA

| Condition                     | Observations |
|-------------------------------|--------------|
| Schools 1 MALE                | 357          |
| school 1 MALE (without M4CID) | 203          |
| school 1 MALE (with M4CID)    | 154          |

### RESULTS

| Sample            | Mean without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes                                                    |
|------------|------------|------------|------------|------------|------------|
| Male for school 1 | less                                                      | CLASS    | 0.03987          | positive???  | Sample analysis with 100 entries, gives a p-value=0.4125 |
| Male for school 1 | less                                                      | TEST     | 0.3295           | no effect    |                                                          |
| Male for school 1 | less                                                      | LAB      | 5.333e-10        | positive     |                                                          |
| Male for school 1 | greater                                                   | BEHAV    | 3.378e-07        | negative     |                                                          |
| observations      |                                                           |          |                  |              |                                                          |

## Inference for SCHOOL 1, gender Female, with or without 4C/ID

### data

| Condition                     | Observations |
|-------------------------------|--------------|
| Schools 1 MALE                | 326          |
| school 1 MALE (without M4CID) | 191          |
| school 1 MALE (with M4CID)    | 135          |

| Sample              | Mean without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| Female for school 1 | less                                                      | CLASS    | 1.638e-06        | positive     |       |
| Female for school 1 | less                                                      | TEST     | 0.0002003        | positive     |       |
| Female for school 1 | less                                                      | LAB      | 2.009e-15        | positive     |       |
| Female for school 1 | greater                                                   | BEHAV    | 0.003575         | negative     |       |

## Inference for SCHOOL 1, grades 7,8 and 9, with or without 4C/ID

### DATA

| Condition                | GRADE 7 |
|--------------------------|---------|
| School 1                 | 222     |
| school 1 (without M4CID) | 123     |
| school 1 (with M4CID)    | 99      |

### RESULTS

| Sample   | Mean for grade 7 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| school 1 | less                                                                  | CLASS    | 0.02623          | positive     |       |
| school 1 | less                                                                  | TEST     | 0.1487           | no effect    |       |
| school 1 | less                                                                  | LAB      | 1.702e-05        | positive     |       |
| school 1 | less                                                                  | BEHAV    | 0.02623          | positive     |       |

| Sample   | Mean for grade 8 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes                                                                                         |
|------------|------------|------------|------------|------------|------------|
| school 1 | less                                                                  | CLASS    | 0.2201           | no effect    | a lot of outliers in the boxplot with the median close to the upper limit???                  |
| school 1 | less                                                                  | TEST     | 0.0006568        | positive     |                                                                                               |
| school 1 | less                                                                  | LAB      | 0.0001906        | positive     | boxplot with the median close to the lower limit???                                           |
| school 1 | greater                                                               | BEHAV    | 2.2e-16          | negative     | a lot of outliers in the boxplot with the median close to the lower limit??? Huge dropdown!!! |

```         
IMPORTANT note: median is close to the first quarter (line on R #651)
```

| Sample   | Mean for grade 9 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| school 1 | less                                                                  | CLASS    | 9.012e-06        | positive     |       |
| school 1 | less                                                                  | TEST     | 0.15258          | no effect    |       |
| school 1 | less                                                                  | LAB      | 2.2e-16          | positive     |       |
| school 1 | greater                                                               | BEHAV    | 0.04297          | positive     |       |

## Inference for SCHOOL 1, RANKS 1, 2, and 3, with or without 4C/ID

There is no scientific justification to construct the categories around
de column CLASS with these definitions:

| categories | condition (CLASS) | RANK | \% data school 1 (683 entries) | \% data school 0 (474 entries)\^\* |
|---------------|---------------|---------------|---------------|---------------|
| 1          | =\<55%            | 1    | 34% (229)                      | 16% (76)                           |
| 2          | 55-70%            | 2    | 41 % (281)                     | 39% (186)                          |
| 3          | \>=70             | 3    | 25 % (173)                     | 45% (212)                          |

Just comparing the schools to double-check for the differences in
schools in competence/adaptation edu system

Conclusion: it seems that students in school 0 are more adapted than
those in school 1.

summary(data_s1_RANK1) \| TEST \| LAB \| BEHAV \| \|---\|---\|---\| \|
Min. :11.0 \| Min. : 0.00 \| Min. : 29.00 \|\
\| 1st Qu.:34.0 \| 1st Qu.:31.00 \| 1st Qu.: 59.00 \| \| Median :42.0 \|
Median :41.00 \| Median : 67.00 \|\
\| Mean :41.79 \| Mean :40.45 \| Mean : 68.04 \| \| 3rd Qu.:48.00 \| 3rd
Qu.:53.00 \| 3rd Qu.: 78.00 \| \| Max. :72.0 \| Max. :80.00 \| Max.
:100.00 \|

summary(data_s1_RANK2) \| TEST \| LAB \| BEHAV \| \|---\|---\|---\| \|
Min. :34.00 \| Min. : 4.00 \| Min. : 40.00 \| \| 1st Qu.:51.00 \| 1st
Qu.:53.00 \| 1st Qu.: 67.00 \| \| Median :57.00 \| Median :60.00 \|
Median : 77.00 \| \| Mean :58.21 \| Mean :59.74 \| Mean : 74.98 \|\
\| 3rd Qu.:67.00 \| 3rd Qu.:67.00 \| 3rd Qu.: 87.00 \| \| Max. :87.00 \|
Max. :87.00 \| Max. :100.00 \|

summary(data_s1_RANK3) \| TEST \| LAB \| BEHAV \| \|---\|---\|---\|---\|
\| Min. : 53.00 \| Min. : 34.00 \| Min. : 64.00 \| \| 1st Qu.: 71.00 \|
1st Qu.: 70.00 \| 1st Qu.: 84.00 \| \| Median : 79.00 \| Median : 80.00
\| Median : 92.00 \| \| Mean : 79.27 \| Mean : 76.52 \| Mean : 89.49 \|
\| 3rd Qu.: 86.00 \| 3rd Qu.: 85.00 \| 3rd Qu.: 96.00 \| \| Max. :100 \|
Max. :100.00 \| Max. :100.00 \|

## Results

| Sample   | Mean for RANK 1 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| school 1 | greater                                                              | TEST     | 0.05162          | no effect    |       |
| school 1 | less                                                                 | LAB      | 8.549e-10        | positive     |       |
| school 1 | greater                                                              | BEHAV    | 1.345e-07        | negative     |       |

## Using a sampling of 68 entries

There are several different results: should I use a for statement, for
the no effect result????

| Sample   | Mean for RANK 2 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| school 1 | less                                                                 | TEST     | 0.3329           | no effect    |       |
| school 1 | less                                                                 | LAB      | 2.991e-07        | positive     |       |
| school 1 | greater                                                              | BEHAV    | 4.755e-14        | negative     |       |

```         
IMPORTANT NOTE: using sampling with 100 random entries confirms the effect
```

| Sample   | Mean for RANK 3 without 4C/ID is greater/less/equal then with 4C/ID? | Variable | p-value (Wilcox) | 4C/ID effect | Notes |
|------------|------------|------------|------------|------------|------------|
| school 1 | less                                                                 | TEST     | 0.5236           | no effect    |       |
| school 1 | less                                                                 | LAB      | 4.814e-07        | positive     |       |
| school 1 | greater                                                              | BEHAV    | 0.003234         | negative     |       |

\`\`\` IMPORTANT NOTE: using sampling with 86 entries confirms the
effect ´´´

## Qualitative

| Qualitative Results                                                                                    | Description   | Notes |
|---------------------------|---------------------------|------------------|
| Students inquire about the teacher                                                                     |               |       |
| teacher available to interact with the students while they are following the online lessons activities |               |       |
| students feel happy to pass to the next level, high motivation                                         |               |       |
| They claim that the way they like to learn                                                             |               |       |
| massive hours of teacher work, more than 55 hours a week                                               | Health issues |       |
| Students help on lessons faults: missing information, fault links                                      |               |       |

This qualitative and quantitative data will be analyzed recurring to
usual statistical analysis and gather qualitative data to reinforce the
main goals of the work.

What others have done and how what you doing fits that The work done so
far shows that the results are not clear. Well normally, the results on
the social side are never a clear 80%. In this case, we are happy if
things are 60% positive.
