The structures and functions of human cognitive architecture have been used to design a variety of novel instructional procedures based on the assumption that working memory load should be reduced and schema construction encouraged. One of this is 4C/ID instructional design which is extensively used in this work. Extensive research exists not only on the theories underlying the 4C/ID model, with results often summarized in specific effects and strategies, but in the effects itself resulting not only in the corroboration or not of those alredy in use but finding new ones that increase the effectiveness of the instruction. Consequently, stakeholders—including teachers, policymakers, and school administrators—can gain valuable insights to enhance teaching practices, improve learning design, and more effectively implement instructional strategies (Kirschner, 2002).

In a wide-ranging meta-analysis, the authors concluded that the Four-Component Instructional Design (4C/ID) model should be promoted in both face-to-face and online learning environments. They found that it has a high impact on performance, irrespective of the academic area, the study's design, or the specific outcome measured. The analysis further revealed that the higher-education level is particularly suitable for the application of the 4C/ID model (Costa, Miranda, Melo, 2022). The same authors showed results that revealed significant differences in learning transfer and a more marked decrease in the perceived mental effort by the students in the learning transfer
tests (Melo, 2018).

Direct Instruction (DI) model used in this work (Merrill, 2007), is a 200 years model with an extensive and profound report of positive impacts in learning. Developed and refined by Engelmann and colleagues over the past 50 years, has been the focus of numerous research studies, systematic reviews, and meta-analyses (Mason, Otero, 2021). Research on the effectiveness of Direct Instruction (DI) consistently provide support for the assertion that all children can learn in a wide variety of populations, in different settings, within numerous subject areas (Coughlin, Cristy, 2011). Furthermore, quantitative mixed models were used to examine literature published from 1966 through 2016 on the effectiveness of Direct Instruction. Analyses were based on 328 studies involving 413 study designs and almost 4,000 effects. Results are reported for the total set and subareas regarding reading, math, language, spelling, and multiple or other academic subjects; ability measures; affective outcomes; teacher and parent views; and single-subject designs. All of the estimated effects were positive and all were statistically significant except results from metaregressions involving affective outcomes (Stockard el al., 2018).

developments

https://link.springer.com/article/10.1007/s10984-021-09373-y#citeas

https://scholar.google.com/scholar_lookup?&title=Cognitive%20architecture%20and%20instructional%20design&journal=Educational%20Psychology%20Review&volume=10&pages=251-296&publication_year=1998&author=Sweller%2CJ&author=Merri%C3%ABnboer%2CJJG&author=Paas%2CF

https://scholar.google.com/scholar_lookup?&title=Ten%20steps%20to%20complex%20learning%3A%20a%20systematic%20approach%20to%20four-component%20instructional%20design&publication_year=2018&author=Merri%C3%ABnboer%2CJJG&author=Kirschner%2CPA

https://noic.com.br/wp-content/uploads/2022/02/Worked_Examples.pdf
